apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  accessID: {{ required "A valid .Values.accessID entry is required!" .Values.accessID | b64enc }}
  accessKey: {{ required "A valid .Values.accessKey entry is required!" .Values.accessKey | b64enc }}
  account: {{ required "A valid .Values.account entry is required!" .Values.account | b64enc }}