apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: {{ .Values.service.name }}